config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :films do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'films#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :film
    belongs_to :user
end

app/models/film.rb
class Film < ApplicationRecord
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :comments
         has_many :commented_films, through: :comments, source: :film
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @film = Film.find(params[:film_id])
        @comment = @film.comments.create(comment_params)
        redirect_to film_path(@film)
    end

    private def comment_params
        params.require(:comment).permit(:username, :body)
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: %i[ show edit update destroy ]

  # GET /films or /films.json
  def index
    @films = Film.all
  end

  # GET /films/1 or /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films or /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to film_url(@film), notice: "Film was successfully created." }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1 or /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to film_url(@film), notice: "Film was successfully updated." }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1 or /films/1.json
  def destroy
    @film.destroy

    respond_to do |format|
      format.html { redirect_to films_url, notice: "Film was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.require(:film).permit(:title, :year, :description, :author, :genre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if film.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.text_field :year %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/new.html.erb
<%= render "form", comment: @comments %>

<br>

<div>
  <%= link_to "Show this film", @film %> |
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/_film.html.erb
<div id="<%= dom_id film %>">
  <p>
    <strong>Title:</strong>
    <%= film.title %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= film.year %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= film.description %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= film.author %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= film.genre %>
  </p>

</div>

app/views/films/_form.html.erb
<%= form_with(model: film) do |form| %>
  <% if film.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
        <% film.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.text_field :year %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :genre, style: "display: block" %>
    <%= form.text_field :genre %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Show this film", @film %> |
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Films</h1>

<div id="films">
  <% @films.each do |film| %>
    <%= render film %>
    <p>
      <%= link_to "Show this film", film %>
    </p>
  <% end %>
</div>

<%= link_to "New film", new_film_path %>

<div> 
  <% if current_user.blank? %> 
    <%= link_to 'Log in', new_user_session_path  %> 
  <% else %> 
    <%= link_to "Log out", destroy_user_session_path,data: {"turbo-method": :delete}, class: "link-secondary smooth" %> 
  <% end %> 
</div>

app/views/films/new.html.erb
<h1>New film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @film %>

<div>
  <%= link_to "Edit this film", edit_film_path(@film) %> |
  <%= link_to "Back to films", films_path %>

  <%= button_to "Destroy this film", @film, method: :delete %>
</div>
<hr>
<h2>All comments</h2>
<% @film.comments.each do |comment| %>
<div class="alret alret-light">
  <p><strong><%= comment.username %></strong>: <%= comment.body %></p>
</div>
<%end%>
<hr>
<h2>Comments</h2>
<%= form_for([@film, @film.comments.build]) do |f| %>
  <p>
    User<br>
    <%= f.text_area(:body, {:class => 'from-control'}) %>
  </p>
  <p>
    Text comment<br>
    <%=f.text_area(:body, {:class => 'form-control'}) %>
    </p>
      
    <p>
    <%= f.submit("Add comment", {:class => 'btn btn-warning'})%>
    </p>
    
    <% end %>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myfilm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>